name: Zilliqa Isolated Server CI - Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  push-to-ecr:
    permissions:
      id-token: write
      contents: write
    name: build
    runs-on: docker
    steps:
    - name: Clean environment
      # Prune the Docker resources created over 10 days before the current execution (change the value for a more/less aggressive cleanup).
      shell: bash
      run: |
        docker system df
        docker system prune -a -f --filter "until=168h"
        docker system df

    - name: 'Checkout scm'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure AWS Credentials
      uses: Zilliqa/gh-actions-workflows/actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ECR_DEPLOYER_ROLE }}
        oidc-role: ${{ secrets.OIDC_ROLE }}
        aws-region: ${{ secrets.AWS_REGION_NEO_SAVANT_IDE }}

    - name: Login to the registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AWS_ACCOUNT_ID_NEO_SAVANT_IDE }}.dkr.ecr.${{ secrets.AWS_REGION_NEO_SAVANT_IDE }}.amazonaws.com

    - name: Image tag
      id: set-tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build Docker images
      run: DOCKER_BUILDKIT=1 docker build -t ${{ secrets.AWS_ACCOUNT_ID_NEO_SAVANT_IDE }}.dkr.ecr.${{ secrets.AWS_REGION_NEO_SAVANT_IDE }}.amazonaws.com/zilliqa-isolated-server:${{ steps.set-tag.outputs.tag }} -f Dockerfile .
      shell: bash
